### PR TITLE
Update recipe to include Python 3.6

### PR DESCRIPTION
**Pull request by guillochon**
At the moment `extinction` is only available for Python 2.7/3.4/3.5.

### CODE REVIEW

**Comment by pkgw** [comment]
D'oh, you're one step ahead of me, James!

**Comment by guillochon** [comment]
PS @kbarbary I'm happy to be added to the maintainers if you'd like

**Comment by kbarbary** [comment]
Thanks! I'll try to add you.

**Comment by kbarbary** [comment]
I don't know if I can add you myself. Can you request to join the `extinction` team here: https://github.com/orgs/conda-forge/teams?utf8=%E2%9C%93&query=extinction ?

**Comment by guillochon** [comment]
I think in principle you can add me to the `meta.yaml` under `maintainers` and stuff should happen automatically? Not sure either.

**Comment by kbarbary** [comment]
Ah, that makes sense; will try!

**Comment by pkgw** [comment]
Yes, I think that's how it works. You might need to run another `conda smithy rerender` but I'm not sure about that — can't hurt, though. (Although as @guillochon can tell you, it's a bit of a pain to set up that command to work since it needs you to configure various API tokens.)

**Pull request merged**
